### ISSUE TITLE
"cli run" should provide an escaped way to pass qemu flags directly

### ISSUE THREAD

**Issue by stefanbucur** [dslab-epfl/chef#37]
For example, to mount an external ISO, the command would work as follows:

```
cli run [...] -q -cdrom -q ~/Downloads/debian-7.8.0-i386-netinst.iso
```

**Comment by ayekat** [comment]
Due to the limitations of how `argparse` was designed and implemented (see also http://bugs.python.org/issue9334), the given example will become

```
ctl run [...] -q=-cdrom -q ~/Downloads/debian-7.8.0-i386-netinst.iso
```

(note the `=` for arguments starting with a dash)

**Comment by stefanbucur** [comment]
Sure, that should be fine.
