### ISSUE TITLE
Remove the ".s2e" symlink from the VM directory

### ISSUE THREAD

**Issue by stefanbucur** [dslab-epfl/chef#38]
Instead, use Qemu's `-drive` flag. Take a look at @pzankov's `rlaunch` script for a concrete example: https://github.com/pzankov/s2e-scripts/blob/master/rlaunch

**Comment by ayekat** [comment]
Since there is a hardcoded limitation in S²E for the `.s2e` file name suffix, we now use that suffix for KVM mode as well instead.
