### ISSUE TITLE
Qemu monitor not accessible in GUI

### ISSUE THREAD

**Issue by stefanbucur** [dslab-epfl/chef#53]
When running S2E in preparation mode, with default arguments, the Qemu monitor is not accessible via Ctl+Alt+2 from the Qemu window. Instead, it is still provided over TCP (`-monitor tcp::12345,server,nowait`), as it was running in headless mode.

**Comment by ayekat** [comment]
That is indeed not a very intelligent behaviour - I'll fix that.
