### ISSUE TITLE
Add support for building the ARM architecture

### ISSUE THREAD

**Issue by stefanbucur** [dslab-epfl/chef#8]

**Comment by ayekat** [comment]
When building S²E, both with the build scripts _and_ with the Makefile, I get the following error:

```
/home/ayekat/chef/src/qemu/s2e/DataCollectorSolver.cpp:40:8: error: unknown type name 'CPUX86State'
extern CPUX86State *env;
       ^
```

`CPUX86State` is defined in `target-i386/cpu.h`, which I assume should never be included in an ARM build. I guess somewhere there needs to be an `#ifdef X86_SPECIFIC_CODE_GUARD_THINGY_MACRO`, but I feel like before I plunge into this, you might have an idea.

**Comment by ayekat** [comment]
44bd6f1 solves the issue. The ARM release builds fine now.

**Comment by stefanbucur** [comment]
Don't forget about the PR.
